Remove unused global variable to fix compilation with GCC 10
GCC defaults to -fno-common, resulting in a compilation error:

CryptSym.h:84: multiple definition of `tpmCryptKeySchedule'

Since the global variable is not used anywhere, it can be removed.